// flow-typed signature: b578024c8f2ecca590c48d44b16817ed
// flow-typed version: <<STUB>>/nedb_v^1.8.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nedb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nedb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nedb/benchmarks/commonUtilities' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/ensureIndex' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/find' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/findOne' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/findWithIn' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/insert' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/loadDatabase' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/remove' {
  declare module.exports: any;
}

declare module 'nedb/benchmarks/update' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/browser-specific/lib/customUtils' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/browser-specific/lib/storage' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/build' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/out/nedb' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/out/nedb.min' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/async' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/chai' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/jquery.min' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/localforage' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/mocha' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/nedb-browser' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/testLoad' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/testPersistence' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/testPersistence2' {
  declare module.exports: any;
}

declare module 'nedb/browser-version/test/underscore.min' {
  declare module.exports: any;
}

declare module 'nedb/lib/cursor' {
  declare module.exports: any;
}

declare module 'nedb/lib/customUtils' {
  declare module.exports: any;
}

declare module 'nedb/lib/datastore' {
  declare module.exports: any;
}

declare module 'nedb/lib/executor' {
  declare module.exports: any;
}

declare module 'nedb/lib/indexes' {
  declare module.exports: any;
}

declare module 'nedb/lib/model' {
  declare module.exports: any;
}

declare module 'nedb/lib/persistence' {
  declare module.exports: any;
}

declare module 'nedb/lib/storage' {
  declare module.exports: any;
}

declare module 'nedb/test_lac/loadAndCrash.test' {
  declare module.exports: any;
}

declare module 'nedb/test_lac/openFds.test' {
  declare module.exports: any;
}

declare module 'nedb/test/cursor.test' {
  declare module.exports: any;
}

declare module 'nedb/test/customUtil.test' {
  declare module.exports: any;
}

declare module 'nedb/test/db.test' {
  declare module.exports: any;
}

declare module 'nedb/test/executor.test' {
  declare module.exports: any;
}

declare module 'nedb/test/indexes.test' {
  declare module.exports: any;
}

declare module 'nedb/test/model.test' {
  declare module.exports: any;
}

declare module 'nedb/test/persistence.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nedb/benchmarks/commonUtilities.js' {
  declare module.exports: $Exports<'nedb/benchmarks/commonUtilities'>;
}
declare module 'nedb/benchmarks/ensureIndex.js' {
  declare module.exports: $Exports<'nedb/benchmarks/ensureIndex'>;
}
declare module 'nedb/benchmarks/find.js' {
  declare module.exports: $Exports<'nedb/benchmarks/find'>;
}
declare module 'nedb/benchmarks/findOne.js' {
  declare module.exports: $Exports<'nedb/benchmarks/findOne'>;
}
declare module 'nedb/benchmarks/findWithIn.js' {
  declare module.exports: $Exports<'nedb/benchmarks/findWithIn'>;
}
declare module 'nedb/benchmarks/insert.js' {
  declare module.exports: $Exports<'nedb/benchmarks/insert'>;
}
declare module 'nedb/benchmarks/loadDatabase.js' {
  declare module.exports: $Exports<'nedb/benchmarks/loadDatabase'>;
}
declare module 'nedb/benchmarks/remove.js' {
  declare module.exports: $Exports<'nedb/benchmarks/remove'>;
}
declare module 'nedb/benchmarks/update.js' {
  declare module.exports: $Exports<'nedb/benchmarks/update'>;
}
declare module 'nedb/browser-version/browser-specific/lib/customUtils.js' {
  declare module.exports: $Exports<'nedb/browser-version/browser-specific/lib/customUtils'>;
}
declare module 'nedb/browser-version/browser-specific/lib/storage.js' {
  declare module.exports: $Exports<'nedb/browser-version/browser-specific/lib/storage'>;
}
declare module 'nedb/browser-version/build.js' {
  declare module.exports: $Exports<'nedb/browser-version/build'>;
}
declare module 'nedb/browser-version/out/nedb.js' {
  declare module.exports: $Exports<'nedb/browser-version/out/nedb'>;
}
declare module 'nedb/browser-version/out/nedb.min.js' {
  declare module.exports: $Exports<'nedb/browser-version/out/nedb.min'>;
}
declare module 'nedb/browser-version/test/async.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/async'>;
}
declare module 'nedb/browser-version/test/chai.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/chai'>;
}
declare module 'nedb/browser-version/test/jquery.min.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/jquery.min'>;
}
declare module 'nedb/browser-version/test/localforage.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/localforage'>;
}
declare module 'nedb/browser-version/test/mocha.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/mocha'>;
}
declare module 'nedb/browser-version/test/nedb-browser.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/nedb-browser'>;
}
declare module 'nedb/browser-version/test/testLoad.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/testLoad'>;
}
declare module 'nedb/browser-version/test/testPersistence.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/testPersistence'>;
}
declare module 'nedb/browser-version/test/testPersistence2.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/testPersistence2'>;
}
declare module 'nedb/browser-version/test/underscore.min.js' {
  declare module.exports: $Exports<'nedb/browser-version/test/underscore.min'>;
}
declare module 'nedb/index' {
  declare module.exports: $Exports<'nedb'>;
}
declare module 'nedb/index.js' {
  declare module.exports: $Exports<'nedb'>;
}
declare module 'nedb/lib/cursor.js' {
  declare module.exports: $Exports<'nedb/lib/cursor'>;
}
declare module 'nedb/lib/customUtils.js' {
  declare module.exports: $Exports<'nedb/lib/customUtils'>;
}
declare module 'nedb/lib/datastore.js' {
  declare module.exports: $Exports<'nedb/lib/datastore'>;
}
declare module 'nedb/lib/executor.js' {
  declare module.exports: $Exports<'nedb/lib/executor'>;
}
declare module 'nedb/lib/indexes.js' {
  declare module.exports: $Exports<'nedb/lib/indexes'>;
}
declare module 'nedb/lib/model.js' {
  declare module.exports: $Exports<'nedb/lib/model'>;
}
declare module 'nedb/lib/persistence.js' {
  declare module.exports: $Exports<'nedb/lib/persistence'>;
}
declare module 'nedb/lib/storage.js' {
  declare module.exports: $Exports<'nedb/lib/storage'>;
}
declare module 'nedb/test_lac/loadAndCrash.test.js' {
  declare module.exports: $Exports<'nedb/test_lac/loadAndCrash.test'>;
}
declare module 'nedb/test_lac/openFds.test.js' {
  declare module.exports: $Exports<'nedb/test_lac/openFds.test'>;
}
declare module 'nedb/test/cursor.test.js' {
  declare module.exports: $Exports<'nedb/test/cursor.test'>;
}
declare module 'nedb/test/customUtil.test.js' {
  declare module.exports: $Exports<'nedb/test/customUtil.test'>;
}
declare module 'nedb/test/db.test.js' {
  declare module.exports: $Exports<'nedb/test/db.test'>;
}
declare module 'nedb/test/executor.test.js' {
  declare module.exports: $Exports<'nedb/test/executor.test'>;
}
declare module 'nedb/test/indexes.test.js' {
  declare module.exports: $Exports<'nedb/test/indexes.test'>;
}
declare module 'nedb/test/model.test.js' {
  declare module.exports: $Exports<'nedb/test/model.test'>;
}
declare module 'nedb/test/persistence.test.js' {
  declare module.exports: $Exports<'nedb/test/persistence.test'>;
}
